[build]
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_API_BASE = "https://content-version-system.sycu-lee.workers.dev/"

[pages]
pages_build_output_dir = "out"