[build]
command = "npm install && npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_API_BASE = "https://content-version-system.sycu-lee.workers.dev/"

[site]
bucket = "out"
entry-point = "."

# Thêm cấu hình cho Cloudflare Pages
[pages]
pages_build_output_dir = "out"  # Phải trùng với thư mục publish ở trên
framework = "nextjs"            # Xác định framework là Next.js